Added INFS4205 review
UQComputingSociety/subject-guide pull request #16
Opened 2016-11-24 00:54 UTC by jack775544

Added INFS4205 course review. Haven't checked if it can compile since LaTeX hasn't finished downloading yet. (I mean 3GB, really?)

2016-11-24 02:14 UTC, wisebaldone commented on tex/courses/subjects/INFS4205.tex
> +Assignment 1 & 15\% & Group Assignment \\
Is their 2 parts to assignment 1?

2016-11-24 02:14 UTC, wisebaldone commented on tex/courses/subjects/INFS4205.tex
> +Assignment 1 & 15\% & Group Assignment \\
This also doesn't add up to 100%

2016-11-24 02:14 UTC, wisebaldone commented on tex/courses/subjects/INFS4205.tex
> +    The final exam is open book and can be quite difficult. Even though the theory behind it is fairly simple as long as you are familiar with the course content, the questions require in depth answe
`\\` at the end of this line pls boss

2016-11-24 03:45 UTC, jack775544 commented on tex/courses/subjects/INFS4205.tex
> +Assignment 1 & 15\% & Group Assignment \\
Copy pasta too hard. Fixed now

2016-11-24 03:46 UTC, jack775544 commented on tex/courses/subjects/INFS4205.tex
> +    The final exam is open book and can be quite difficult. Even though the theory behind it is fairly simple as long as you are familiar with the course content, the questions require in depth answe
We wouldn't have this issue with markdown :/
Fixed

2016-11-24 03:51 UTC, draganmarjanovic commented on tex/courses/subjects/INFS4205.tex
> +    This course provides an overview on the of the theory of high dimensional databases, with a focus on indexing and searching. This content builds on the theory taught in INFS2200 and it is highly
"on the of the" rephrase

2016-11-24 03:51 UTC, draganmarjanovic commented on tex/courses/subjects/INFS4205.tex
> +    This course provides an overview on the of the theory of high dimensional databases, with a focus on indexing and searching. This content builds on the theory taught in INFS2200 and it is highly
"components of INFS2200" sounds better IMO

2016-11-24 03:53 UTC, draganmarjanovic requested changes
Parts of line 15 need rewording IMO.

2016-11-25 10:13 UTC, wisebaldone commented
@draganmarjanovic can you re-review the changes

2016-12-02 10:39 UTC, draganmarjanovic requested changes
Aside from this - all good.

2016-12-02 10:39 UTC, draganmarjanovic commented on tex/courses/subjects/INFS4205.tex
> +    The final exam is open book and can be quite difficult. Even though the theory behind it is fairly simple, as long as you are familiar with the course content, the questions require in depth answ
" as long as you are familiar with the course content" should either be in brackets IMO or completely removed.

2016-12-03 03:22 UTC, jack775544 commented
I think it is all good now

2016-12-03 03:23 UTC, wisebaldone commented
LGTM, im taking dragan as one piece of three

2016-12-03 03:23 UTC, merged

2016-12-03 03:24 UTC, draganmarjanovic commented
👍