Basic LaTEX Template
UQComputingSociety/subject-guide pull request #4
Opened 2016-09-08 06:57 UTC by ashfordneil

Not sure if we still want to use LaTEX, but if we do, this is a starting template.

2016-09-08 12:19 UTC, wisebaldone commented
@matthew-lake, please review this for us boss

2016-09-10 05:48 UTC, wisebaldone commented
Few recommendations before I can `LGTM` this.

1) Seems your are using the old license instead of the MIT license.
2) Seems your listing the University of Queensland as the authors instead of the University of Queensland Computer Society as the collective author.

other than that, looks good for a starter.

2016-09-15 03:14 UTC, TRManderson commented on tex/courses/CSSE1001.tex
> +%%% COMPANIOUN COURSES
Spelling

2016-09-15 03:17 UTC, TRManderson commented on tex/misc/titlePage.tex
> +{\Large \textsc{The University of Queensland}}\par % Author name
As @wisebaldone said, pls fix

2016-09-15 03:17 UTC, TRManderson requested changes

2016-09-15 03:26 UTC, TRManderson approved these changes

2016-09-15 03:26 UTC, merged